name: argon_flutter
description: Free Flutter App Template created by Creative Tim.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^2.2.1
  url_launcher: ^5.5.2
  scrollable_positioned_list: ^0.1.7
  sqflite: ^2.0.2
  shared_preferences: ^2.0.13
  path_provider: ^2.0.8
  crypto: ^3.0.1
  date_field: ^2.1.3
  select_form_field: "^2.2.0"
  easy_mask: ^2.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  http: ^0.13.4
  geocoding: ^1.0.5
  tuple: ^1.0.2  
  cupertino_icons: ^0.1.3
  connectivity_plus: any
  data_connection_checker: any
  flutter_easyloading : any
  connectivity_wrapper: any

  positioned_tap_detector_2: ^1.0.0
  transparent_image: ^1.0.0
  async: ^2.1.0
  flutter_image: ^3.0.0
  vector_math: ^2.0.0
  proj4dart: ^1.0.4
  meta: ^1.1.0
  collection: ^1.14.0
  intl: ^0.17.0
  date_format: ^2.0.5
  flutter_map: any
  latlong: ^0.6.1
  latlong2: ^0.8.0
  geolocator: ^5.1.5
  # flutter_mapbox_navigation: ^0.0.26

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/img/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - data/db.sqlite3
   - assets/img/pro-background.png
   - assets/ca/lets-encrypt-r3.pem
   - assets/img/onboard-background.png
   - assets/img/logo-android.png
   - assets/img/logo-ios.png
   - assets/img/logo-nbs.png
   - assets/img/logo-argon.png
   - assets/img/Logo.jpg
   - assets/img/profile-screen-avatar.jpg
   - assets/img/profile-screen-bg.png
   - assets/img/register-bg.png
   - assets/img/chat-avatar.jpeg
   - assets/img/argon-logo.png
   - assets/img/logo.png
   - assets/img/screen1.png
   - assets/img/argon-logo-onboarding.png
   - assets/img/bg-2.jpg
   - assets/img/forest.jpg
   - assets/img/forest1.jpg
   - assets/img/forest2.jpg
   - assets/img/user-icon-1.png
   - assets/img/user-icon-2.png


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 600

